spring.application.name=Movies

//server.servelet.context-path=/api/v1
# Configuración MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/movieDb
spring.datasource.username=root
spring.datasource.password=rami123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

spring.sql.init.mode=never
spring.sql.init.data-locations=classpath:db/users.sql,classpath:db/movies.sql
#spring.jpa.defer-datasource-initialization=true

logging.level.org.springframework.jdbc=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type=TRACE

